# Site settings
title: Mohammad Minhazul Haq
description: Portfolio of Mohammad Minhazul Haq
favicon: /assets/img/avatar.JPG
baseurl: https://minhazul-haq.github.io
url: https://minhazul-haq.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown
exclude: [vendor]
